repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(yml|yaml)$
  - repo: local
    hooks:
      - id: linkcheck
        name: Check for broken links
        entry: scripts/linkcheck.sh
        language: script
        pass_filenames: false
        always_run: true
        verbose: true
